[IRC]

	[irc.freenode]
	Server="irc.freenode.net:6697"
	Nick="${IRC_NICK}"
	UseTLS=true
	UseSASL=false
	SkipTLSVerify=true
	NickServPassword="${IRC_NICKSERV_PASSWORD}"
	RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

[Matrix]

	[Matrix.pcworms]
	Server="${MATRIX_SERVER}"
	Login="${MATRIX_LOGIN}"
	Password="${MATRIX_PASSWORD}"
	RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

[Telegram]
	[Telegram.pcworms]
	Token="${TELEGRAM_TOKEN}"
	RemoteNickFormat="[{PROTOCOL}] <{NICK}> "
	MessageFormat="HTMLNick"

[[gateway]]
name="gateway1"
enable=true

[[gateway.inout]]
account="IRC.freenode"
channel="#pcworms"

[[gateway.inout]]
account="Matrix.pcworms"
channel="#pcworms:mozilla.org"

[[gateway.inout]]
account="Telegram.pcworms"
channel="-1001319899000"

[general]

Plus=true
