[IRC]

Enable=true
Server="irc.freenode.net"
Nick="${IRC_NICK}"
UseTLS=true
UseSASL=false
SkipTLSVerify=true
NickServPassword="${IRC_NICKSERV_PASSWORD}"
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

[Matrix]

Server="${MATRIX_SERVER}"
Login="${MATRIX_LOGIN}"
Password="${MATRIX_PASSWORD}"
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

[Telegram]
Token="${TELEGRAM_TOKEN}"
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "
MessageFormat="HTMLNick"

[[gateway]]
name="gateway1"
enable=true

[[gateway.inout]]
account="IRC"
channel="#pcworms"

[[gateway.inout]]
account="Matrix"
channel="#pcworms:mozilla.org"

[[gateway.inout]]
account="Telegram"
channel="-1001319899000"

[general]

Plus=true
